
all:
	cd $(SWDIR)\c\mkbase
	nmake -f Makefile.watcom
	cd $(SWDIR)\c\txtcalc
	nmake -f Makefile.watcom
	cd $(SWDIR)\c
clean:
	cd $(SWDIR)\c\txtcalc
	nmake -f Makefile.watcom clean
	cd $(SWDIR)\c\mkbase
	nmake -f Makefile.watcom clean
	cd $(SWDIR)\c


