
all:
	cd $(SWDIR)\c\mkbase
	nmake /f Makefile.msvc
	cd $(SWDIR)\c\txtcalc
	nmake /f Makefile.msvc
	cd $(SWDIR)\c
clean:
	cd $(SWDIR)\c\txtcalc
	nmake /f Makefile.msvc clean
	cd $(SWDIR)\c\mkbase
	nmake /f Makefile.msvc clean
	cd $(SWDIR)\c


