	

all:
	javac --module-path $(JFX_MODULE_PATH) --add-modules=$(JFX_MODULES) tstjfx/Fx2DShape.java

start:
	java -cp . --module-path $(JFX_MODULE_PATH) --add-modules=$(JFX_MODULES) tstjfx.Fx2DShape

clean:
	rm -rf tstjfx/Fx2DShape.class

